//! MemoryProvider trait - standardized interface for memory storage backends.
//!
//! This trait extends the original `MemoryStore` trait with additional methods
//! that cover all operations the Runtime needs from a memory engine:
//! - Hybrid retrieval (vector + full-text)
//! - Memory store tool entry (conflict detection, dedup, node creation)
//! - Ambiguous conflict confirmation
//! - Experience generalization (Path C)
//! - Node CRUD (procedural, autobiographical, edges)
//! - Consolidation lifecycle (start, stop, notify, run offline)
//!
//! Implementations: GrafeoStore (default), InMemoryProvider (testing),
//! RemoteMemoryProvider (future).
//!
//! Design ref: ADR-051

use std::time::Duration;

use acowork_core::error::Result;
use async_trait::async_trait;


use crate::consolidation::{
    EmbeddingFn, GeneralizationConfig, GeneralizationResult, MemoryStoreInput, MemoryStoreResult,
    OfflineConsolidationConfig, OfflineConsolidationResult, SchedulerConfig, TripleExtractorLlm,
};
use crate::types::{
    AutobioCategory, AutobiographicalNode, DecayConfig, DecayScanResult, Episode,
    KnowledgeNode, MemoryQuery, ProceduralNode, PurgeResult, SearchResult, StoreHealth, StoreStats,
};

/// MemoryProvider trait - standardized interface for memory storage backends.
///
/// This is the primary abstraction layer between the Runtime and the memory
/// engine. The Runtime holds a `dyn MemoryProvider` and never accesses the
/// concrete storage engine (GrafeoStore) directly.
///
/// Implementations can be: GrafeoStore (current), InMemoryProvider (testing),
/// RemoteMemoryProvider (future), or any custom storage engine.
///
/// Design ref: ADR-051, docs/05-memory.md §10.3
#[async_trait]
pub trait MemoryProvider: Send + Sync {
    // ── Episodic layer ───────────────────────────────────────────────────

    /// Store an interaction episode.
    ///
    /// Episode content is stored as-is.
    /// Embedding is generated by Runtime and passed in.
    fn store_episode(&self, episode: &Episode) -> Result<()>;

    /// Search episodic memories by query.
    fn search_episodes(&self, query: &MemoryQuery) -> Result<Vec<SearchResult>>;

    /// Mark episodes as consolidated.
    fn mark_consolidated(&self, ids: &[u64]) -> Result<()>;

    /// Cleanup consolidated episodes older than the given duration.
    fn cleanup_episodes(&self, older_than: Duration) -> Result<u64>;

    /// Retrieve episodes for conversation history.
    ///
    /// If `session_id` is provided, returns episodes for that session ordered by
    /// timestamp descending. Otherwise returns all episodes across all sessions.
    fn get_episodes(&self, session_id: Option<&str>, limit: usize) -> Result<Vec<Episode>>;

    // ── Semantic layer ───────────────────────────────────────────────────

    /// Store or update a knowledge node (Fact/Preference/Relation).
    ///
    /// Fact nodes are automatically deduplicated by (subject, predicate).
    fn store_knowledge(&self, node: &KnowledgeNode) -> Result<()>;

    /// Store or update a procedural memory node.
    fn store_procedural(&self, node: &ProceduralNode) -> Result<()>;

    /// Store or update an autobiographical memory node.
    ///
    /// Status is forced to Active (enforced by schema).
    fn store_autobiographical(&self, node: &AutobiographicalNode) -> Result<()>;

    // ── Unified retrieval ───────────────────────────────────────────────

    /// Hybrid search: vector + full-text + RRF fusion.
    ///
    /// Searches across all labels (Episodic/Knowledge/Procedural/Autobiographical).
    fn hybrid_search(&self, query: &MemoryQuery) -> Result<Vec<SearchResult>>;

    /// Graph expansion: diffuse from seed nodes along edges.
    ///
    /// # Arguments
    /// * `seeds` - Seed nodes from hybrid_search
    /// * `hops` - Maximum expansion depth (capped at 3)
    fn graph_expand(&self, seeds: &[SearchResult], hops: u8) -> Result<Vec<SearchResult>>;

    // ── Forgetting ───────────────────────────────────────────────────────

    /// Run decay scan with the given configuration.
    ///
    /// Implements: decay_score = importance × activity_signal
    /// where activity_signal = clamp(recency_boost + access_boost, floor, 1.0)
    fn run_decay_scan(&self, config: &DecayConfig) -> Result<DecayScanResult>;

    /// Reactivate a Dormant node back to Active.
    fn reactivate_node(&self, node_id: u64) -> Result<()>;

    /// Purge expired Dormant nodes.
    ///
    /// Node is purged if: dormant_age > config.purge_after AND
    /// importance < config.purge_importance_threshold
    fn purge_expired(&self, max_dormant_age: Duration) -> Result<PurgeResult>;

    // ── Lifecycle ───────────────────────────────────────────────────────

    /// Health check for monitoring and diagnostics.
    fn health_check(&self) -> Result<StoreHealth>;

    /// Storage statistics (node counts, storage size, index status).
    fn stats(&self) -> Result<StoreStats>;

    /// Close the store, flushing pending writes.
    fn close(&self) -> Result<()>;

    // ── Phase 1: Hybrid retrieval (extended) ────────────────────────────

    /// Run hybrid retrieval (vector + full-text), returning (node_id, score) pairs.
    ///
    /// `#[allow(clippy::too_many_arguments)]`: this is a thin trait-method
    /// signature whose parameters (query, embedding, weights, filter) are
    /// semantically independent retrieval inputs; bundling them into a
    /// struct would obscure the call sites without reducing real complexity.
    #[allow(clippy::too_many_arguments)]
    fn hybrid_search_full(
        &self,
        label: &str,
        query_text: &str,
        embedding: &[f32],
        k: usize,
        text_weight: f64,
        vector_weight: f64,
        min_score: Option<f32>,
    ) -> Result<Vec<(u64, f64)>>;

    /// Pure text retrieval with label filter.
    fn text_search_with_filter(
        &self,
        label: &str,
        field: &str,
        query_text: &str,
        k: usize,
        min_score: Option<f32>,
    ) -> Result<Vec<(u64, f64)>>;

    // ── Phase 1: memory_store tool entry ────────────────────────────────

    /// Process a `memory_store` tool call: content -> conflict detection / dedup
    /// -> node creation.
    ///
    /// Returns `None` if the content was skipped as a duplicate.
    fn process_memory_store(&self, input: &MemoryStoreInput) -> Result<Option<MemoryStoreResult>>;

    // ── Phase 1: Ambiguous conflict confirmation ────────────────────────

    /// Check whether any ambiguous conflicts are pending user confirmation.
    fn should_trigger_confirmation(&self) -> Result<bool>;

    /// Generate a human-readable hint for the pending ambiguous conflict.
    fn generate_confirmation_hint(&self) -> Result<Option<String>>;

    // ── Phase 1: Experience generalization (Path C) ─────────────────────

    /// Run experience generalization: extract behavior patterns from
    /// repeated episodes and create/boost ProceduralNodes.
    async fn run_generalization(
        &self,
        session_id: Option<&str>,
        embedding_fn: &EmbeddingFn,
        config: &GeneralizationConfig,
    ) -> Result<GeneralizationResult>;

    /// Compress old History nodes into summaries to reclaim space.
    fn compress_history_nodes(&self, keep_recent: usize) -> Result<usize>;

    // ── Phase 1: Node CRUD ──────────────────────────────────────────────

    /// Retrieve all procedural memory nodes.
    fn get_all_procedural_nodes(&self) -> Result<Vec<ProceduralNode>>;

    /// Find procedural nodes matching a trigger condition.
    fn find_procedural_by_trigger(&self, trigger: &str, limit: usize) -> Result<Vec<ProceduralNode>>;

    /// Get a single procedural node by ID.
    fn get_procedural(&self, node_id: u64) -> Result<Option<ProceduralNode>>;

    /// Update a procedural memory node.
    fn update_procedural(&self, node: &ProceduralNode) -> Result<()>;

    /// Find an autobiographical node by its key (e.g., "name", "language").
    fn find_autobiographical_by_key(&self, key: &str) -> Result<Option<AutobiographicalNode>>;

    /// Find autobiographical nodes by category.
    fn find_autobiographical_by_category(
        &self,
        category: AutobioCategory,
    ) -> Result<Vec<AutobiographicalNode>>;

    /// Update an autobiographical memory node.
    fn update_autobiographical(&self, node: &AutobiographicalNode) -> Result<()>;

    /// Create a memory edge between two nodes.
    fn create_memory_edge(
        &self,
        from: u64,
        to: u64,
        edge_type: &str,
        properties: Vec<(&str, String)>,
    ) -> Result<()>;

    // ── Phase 1 C4: Retrieval pipeline support ──────────────────────────

    /// Graph expansion from seed nodes using hint-based configuration.
    ///
    /// Returns `(node_id, accumulated_score, label)` tuples for expanded nodes.
    /// The `hint_type` parameter controls spreading configuration ("s", "f",
    /// "r", "i") and is translated to internal expansion parameters by the
    /// Provider implementation.
    ///
    /// This method bridges the gap between `hybrid_search_full()` (which
    /// returns raw `(u64, f64)` pairs) and the need for graph-extended
    /// results with labels. ADR-051 C4.
    fn graph_expand_seeded(
        &self,
        seeds: &[(u64, f64)],
        hint_type: &str,
    ) -> Result<Vec<(u64, f64, String)>>;

    /// Extract human-readable content from a node by ID.
    ///
    /// This abstracts the property-extraction logic that was previously
    /// in Runtime's `extract_node_content()` helper. Each Provider
    /// implementation decides how to render node content (e.g., combining
    /// `subject + predicate + object` for Knowledge nodes, or
    /// `category: key: value` for Autobiographical nodes).
    ///
    /// Returns `None` if the node does not exist.
    fn get_node_content(&self, node_id: u64) -> Result<Option<String>>;

    /// Get the `session_id` property of a node.
    ///
    /// Used by the retrieval pipeline to filter out nodes belonging to
    /// the current session (prevents re-injecting compaction summaries
    /// that are already in the context window).
    ///
    /// Returns `None` if the node has no `session_id` property or does
    /// not exist.
    fn get_node_session_id(&self, node_id: u64) -> Result<Option<String>>;

    /// Apply PageRank topology boost to re-rank retrieval scores.
    ///
    /// Modifies `scores` in-place: `new_score = original * (1 - weight) +
    /// pagerank * weight`. This is a topology-aware re-ranking step that
    /// boosts well-connected nodes. ADR-051 C4.
    fn apply_pagerank_boost(
        &self,
        scores: &mut [(u64, f64)],
        weight: f64,
    ) -> Result<()>;

    // ── Phase 1: Consolidation lifecycle ────────────────────────────────
    //
    // ConsolidationScheduler is internal to the Provider implementation.
    // Different engines may have entirely different consolidation strategies.
    // The Runtime only controls start/stop/notify via these trait methods.

    /// Start background consolidation (managed internally by the Provider).
    /// The config is passed by the Runtime, but execution details are
    /// determined by the Provider.
    fn start_consolidation(&self, config: &SchedulerConfig) -> Result<()>;

    /// Stop background consolidation.
    fn stop_consolidation(&self);

    /// Notify the Provider that the agent is active, resetting the idle timer.
    async fn notify_consolidation_active(&self);

    /// Get the number of pending consolidation nodes (for scheduling decisions).
    fn get_pending_consolidation_count(&self) -> Result<usize>;

    /// Run one offline consolidation pass.
    async fn run_offline_consolidation(
        &self,
        offline_config: &OfflineConsolidationConfig,
        llm: Option<&dyn TripleExtractorLlm>,
        embedding_fn: Option<EmbeddingFn>,
        gen_config: Option<&GeneralizationConfig>,
    ) -> Result<OfflineConsolidationResult>;

}
