//! Cross-language wire-format regression test for the
//! `AttachedItem` MQTT contract (ADR-046).
//!
//! The Desktop frontend serializes each `AttachedItem` via
//! `toWireAttachedItems` in `apps/acowork-desktop/src/lib/types.ts`
//! and publishes the result on `params_json.attached_items` over MQTT.
//! The Runtime parses each entry via
//! `serde_json::from_value::<AttachedItem>(...).ok()` at
//! `core/acowork-runtime/src/startup/gateway_loop.rs:813-820` —
//! failures are **silently filtered**, so a shape mismatch surfaced
//! as "every attachment vanishes after send" rather than a visible
//! error.
//!
//! To guard against that, the Desktop ships a canonical fixture
//! generated by `scripts/dump-attached-wire.mts`:
//!   `core/acowork-core/tests/fixtures/desktop_attached_items.json`
//! This test loads that fixture and asserts:
//!   1. every entry deserializes into the expected `AttachedItem`
//!      variant (lock the type tag + variant payload);
//!   2. the **field-name style is camelCase** for inner fields, not
//!      snake_case (lock the field names). This is the actual bug
//!      guard — without it, the snake_case variant would still parse
//!      to `AttachedItem::FileUpload { document_id: "" }` (empty
//!      default), with all fields zeroed.
//!   3. the original JSON bytes are byte-for-byte identical to the
//!      serialized Rust `AttachedItem` (round-trip lock).
//!
//! If you change the wire format, regenerate the fixture with:
//!   `tsx apps/acowork-desktop/scripts/dump-attached-wire.mts`
//! and confirm the change is intentional. The Rust test below is the
//! single source of truth for what the runtime will accept.

use acowork_core::protocol::AttachedItem;
use serde_json::Value;
use std::path::PathBuf;

/// Each variant must be locked at the byte level: the fixture entry
/// must round-trip through `AttachedItem` and back, AND the inner
/// field names must be camelCase (the bug the original implementation
/// regressed against).
#[test]
fn desktop_attached_items_fixture_roundtrips() {
    let fixture_path = fixture_path();
    let raw = std::fs::read_to_string(&fixture_path).unwrap_or_else(|e| {
        panic!(
            "fixture missing at {} — run `tsx apps/acowork-desktop/scripts/dump-attached-wire.mts` to regenerate: {}",
            fixture_path.display(),
            e
        )
    });

    let entries: Vec<Value> = serde_json::from_str(&raw).unwrap_or_else(|e| {
        panic!("fixture {} is not a JSON array: {}", fixture_path.display(), e)
    });

    // The fixture must cover all 5 variants — if a future change drops
    // one, the test fails loudly instead of silently regressing
    // coverage.
    let mut counts = std::collections::HashMap::<&str, usize>::new();
    for entry in &entries {
        let t = entry
            .get("type")
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("entry missing `type` field: {}", entry));
        *counts.entry(t).or_default() += 1;
    }
    assert_eq!(counts.get("file_upload").copied().unwrap_or(0), 1, "expected 1 file_upload fixture");
    assert_eq!(counts.get("image_upload").copied().unwrap_or(0), 2, "expected 2 image_upload fixtures (with and without dims)");
    assert_eq!(counts.get("attached_file").copied().unwrap_or(0), 1, "expected 1 attached_file fixture");
    assert_eq!(counts.get("attached_selection").copied().unwrap_or(0), 2, "expected 2 attached_selection fixtures (range + collapsed)");
    assert_eq!(counts.get("attached_folder").copied().unwrap_or(0), 1, "expected 1 attached_folder fixture");

    // Field-name lock: the runtime deserializer accepts the values, but
    // a snake_case mistake would let every field default to ""/0 and the
    // runtime would happily persist it. So we explicitly check the wire
    // shape — every variant must carry the `type` tag plus its camelCase
    // inner fields. Anything else (extra/missing keys) means the
    // desktop `toWireAttachedItems` and the runtime `AttachedItem`
    // enum drifted apart.
    //
    // Each entry is `(variant, required_keys, optional_keys)`. The wire
    // MUST include every required key and only keys from the union
    // (required ∪ optional) — anything else (e.g. a snake_case
    // regression) is a hard failure.
    let camel_required: &[(&str, &[&str], &[&str])] = &[
        (
            "file_upload",
            &["type", "documentId", "filename", "format", "sizeBytes"],
            &["clientId"],
        ),
        (
            "image_upload",
            // `width` / `height` are explicit `Option<u32>` on the Rust
            // side (`#[serde(default, skip_serializing_if =
            // "Option::is_none")]`), and the desktop only ships them
            // when the renderer can measure the natural pixel size —
            // ADR-046 §2.5. Treat them as optional-but-camelCase.
            &["type", "documentId", "filename", "format", "sizeBytes"],
            &["width", "height", "clientId"],
        ),
        ("attached_file", &["type", "absPath", "name"], &["clientId"]),
        (
            "attached_selection",
            &["type", "absPath", "name", "startLine", "endLine"],
            &["clientId"],
        ),
        ("attached_folder", &["type", "absPath", "name"], &["clientId"]),
    ];
    let mut shape: std::collections::HashMap<
        &str,
        (&[&str], &[&str]),
    > = std::collections::HashMap::new();
    for (t, required, optional) in camel_required {
        shape.insert(*t, (*required, *optional));
    }

    for entry in &entries {
        let obj = entry
            .as_object()
            .unwrap_or_else(|| panic!("entry not an object: {}", entry));
        let t = obj
            .get("type")
            .and_then(|v| v.as_str())
            .expect("entry missing `type`");
        let (required, optional) = shape
            .get(t)
            .copied()
            .unwrap_or_else(|| panic!("fixture contains unknown type: {}", t));
        let actual_keys: std::collections::BTreeSet<&str> =
            obj.keys().map(|k| k.as_str()).collect();
        let required_set: std::collections::BTreeSet<&str> =
            required.iter().copied().collect();
        let optional_set: std::collections::BTreeSet<&str> =
            optional.iter().copied().collect();
        let allowed: std::collections::BTreeSet<&str> = required_set
            .union(&optional_set)
            .copied()
            .collect();

        // Required must all be present.
        let missing: Vec<&&str> = required
            .iter()
            .filter(|k| !actual_keys.contains(*k))
            .collect();
        assert!(
            missing.is_empty(),
            "variant `{}` missing required wire keys {:?}; got {:?}",
            t, missing, actual_keys
        );
        // Anything else is a hard failure: an unexpected extra key is
        // either a snake_case residue (silent-drop risk) or a schema
        // drift the runtime struct doesn't know about.
        let extra: Vec<&&str> = actual_keys
            .difference(&allowed)
            .collect();
        assert!(
            extra.is_empty(),
            "variant `{}` has unexpected wire keys {:?}; allowed = {:?}",
            t, extra, allowed
        );

        // Belt-and-braces: reject any snake_case residue on any key.
        // If this fires, `toWireAttachedItems` regressed and the runtime
        // will silently drop every item with `.ok()`.
        for k in obj.keys() {
            assert!(
                !looks_like_snake_case(k),
                "field `{}` on variant `{}` looks snake_case; runtime will \
                 silently drop this entry via `from_value().ok()`",
                k, t
            );
        }
    }

    // Round-trip lock: every fixture entry must deserialize into the
    // expected variant with the expected payload, AND the Rust
    // serializer must produce an exact byte-identical object back.
    for entry in &entries {
        let parsed: AttachedItem = serde_json::from_value(entry.clone())
            .unwrap_or_else(|e| panic!("runtime rejected fixture entry {}: {}", entry, e));
        let reserialized = serde_json::to_value(&parsed)
            .unwrap_or_else(|e| panic!("re-serialize failed for {:?}: {}", parsed, e));

        // Object-key equality is what matters (value-level too, for
        // safety). JSON object comparison ignores key order so we use a
        // canonical re-serialize + comparison.
        assert_eq!(
            entry, &reserialized,
            "round-trip mismatch: fixture != serde(AttachedItem)\n\
             fixture:  {}\n\
             reserial: {}",
            entry, reserialized
        );

        match &parsed {
            AttachedItem::FileUpload { document_id, filename, format, size_bytes, .. } => {
                assert!(!document_id.is_empty(), "file_upload.document_id must be populated");
                assert!(!filename.is_empty(), "file_upload.filename must be populated");
                assert!(!format.is_empty(), "file_upload.format must be populated");
                assert!(*size_bytes > 0, "file_upload.size_bytes must be positive");
            }
            AttachedItem::ImageUpload { document_id, size_bytes, width, height, .. } => {
                assert!(!document_id.is_empty(), "image_upload.document_id must be populated");
                assert!(*size_bytes > 0, "image_upload.size_bytes must be positive");
                // width/height are intentionally Option<u32> — both
                // Some and None must round-trip cleanly.
                match (width, height) {
                    (Some(w), Some(h)) => assert!(*w > 0 && *h > 0),
                    (None, None) => {}
                    _ => panic!("image_upload width/height must both be Some or both None"),
                }
            }
            AttachedItem::AttachedFile { abs_path, name, .. } => {
                assert!(!abs_path.is_empty(), "attached_file.abs_path must be populated");
                assert!(!name.is_empty(), "attached_file.name must be populated");
            }
            AttachedItem::AttachedSelection { abs_path, name, start_line, end_line, .. } => {
                assert!(!abs_path.is_empty(), "attached_selection.abs_path must be populated");
                assert!(!name.is_empty(), "attached_selection.name must be populated");
                assert!(*start_line >= 1, "start_line must be 1-based");
                assert!(*end_line >= *start_line, "end_line must be >= start_line");
            }
            AttachedItem::AttachedFolder { abs_path, name, .. } => {
                assert!(!abs_path.is_empty(), "attached_folder.abs_path must be populated");
                assert!(!name.is_empty(), "attached_folder.name must be populated");
            }
        }
    }
}

/// Lock the discriminant tag's snake_case style independently. The enum
/// uses `#[serde(rename_all = "snake_case")]` on the tag, so a
/// `file_upload`-vs-`fileUpload` mistake here would surface as a
/// deserialization failure — but as a separate test for visibility.
#[test]
fn attached_items_type_tag_is_snake_case() {
    let fixture_path = fixture_path();
    let raw = std::fs::read_to_string(&fixture_path).expect("fixture missing");
    let entries: Vec<Value> = serde_json::from_str(&raw).expect("fixture must be a JSON array");
    for entry in &entries {
        let t = entry.get("type").and_then(|v| v.as_str()).expect("`type` field");
        assert!(
            !t.chars().any(|c| c.is_ascii_uppercase()),
            "type tag `{}` must be snake_case (enum-level `rename_all = snake_case`)",
            t
        );
    }
}

fn fixture_path() -> PathBuf {
    // CARGO_MANIFEST_DIR is `<repo>/core/acowork-core`; the fixture
    // lives next to this test under `tests/fixtures/`.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("desktop_attached_items.json")
}

/// A reasonable snake_case detector for field names. Used by the
/// round-trip test to defend against the regression that motivated
/// this whole fixture: emitting `document_id` instead of
/// `documentId` lets the runtime deserializer silently default all
/// fields, which surfaces as "no attachment appears in JSONL after
/// send" — no exception, no log, just data loss.
fn looks_like_snake_case(key: &str) -> bool {
    if key.starts_with('_') {
        return false;
    }
    // snake_case = all-lowercase with underscores separating words.
    // camelCase = lowercase first letter, no underscores.
    // Per `#[serde(rename_all = "camelCase")]` on each variant, the
    // only underscore-bearing key on the wire would be a regression.
    key.contains('_')
}